version: '3.9'
services:
  datascience-notebook:
    # Specify where the project parent directory is, and where the Dockerfile
    # is within that structure.
    build:
      context: ../
      dockerfile: ./environment/Dockerfile
    # Map port 8888 in the container to port 10000 on the host machine.
    # This is what makes jupyter accessible at localhost:10000
    ports:
      - "10000:8888"
    # This connects the Jupyter notebook directory to the host machine so
    # that can all be checked into version control.
    volumes:
      # Link the analysis and data directories into the container
      - '../analysis:/home/jovyan/analysis'
      - '../data:/home/jovyan/data'
      # Make the server config file available in the correct place
      - '../environment/jupyter_server_config.py:/home/jovyan/.jupyter/jupyter_server_config.py'
